[tool.poetry]
name = "pore"
version = "0.1.0"
description = "Search the RCSB for pores"
authors = ["Aron Broom <broomsday@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.9"
typer = "^0.4.0"
pymongo = "^3.12.0"
tqdm = "^4.62.3"
biopython = "^1.79"
pyntcloud = "^0.1.5"
requests = "^2.27.1"
progressbar = "^2.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
